tekst = str(input("Sisesta tekst: "))
hind = float(input("Sisestage 1 kauba hind: "))
kogus = int(input("Sisesta kogus: "))
riik = input("Sisestage riigi kood: ").upper()
koguhind = hind * kogus
print("See on teie tekst: " + tekst)
print("Ühe kauba hind on: " + str(hind) )
print("Teie kogus on: " + str(kogus) )
print("Kogu kauba hind on : " + str(koguhind))
print("Teie riigi kood on" + str(riik))
